#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EAD_Assignment_No_3.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Mosques")]
	public partial class MosqueListClassDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMosqueList(MosqueList instance);
    partial void UpdateMosqueList(MosqueList instance);
    partial void DeleteMosqueList(MosqueList instance);
    #endregion
		
		public MosqueListClassDataContext() : 
				base(global::EAD_Assignment_No_3.Properties.Settings.Default.MosquesConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MosqueListClassDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MosqueListClassDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MosqueListClassDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MosqueListClassDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MosqueList> MosqueLists
		{
			get
			{
				return this.GetTable<MosqueList>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MosqueList")]
	public partial class MosqueList : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private string _Area;
		
		private string _Address;
		
		private string _Fajar;
		
		private string _Zuhar;
		
		private string _Asar;
		
		private string _Maghrib;
		
		private string _Isha;
		
		private string _Jumma;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnAreaChanging(string value);
    partial void OnAreaChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnFajarChanging(string value);
    partial void OnFajarChanged();
    partial void OnZuharChanging(string value);
    partial void OnZuharChanged();
    partial void OnAsarChanging(string value);
    partial void OnAsarChanged();
    partial void OnMaghribChanging(string value);
    partial void OnMaghribChanged();
    partial void OnIshaChanging(string value);
    partial void OnIshaChanged();
    partial void OnJummaChanging(string value);
    partial void OnJummaChanged();
    #endregion
		
		public MosqueList()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Area", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Area
		{
			get
			{
				return this._Area;
			}
			set
			{
				if ((this._Area != value))
				{
					this.OnAreaChanging(value);
					this.SendPropertyChanging();
					this._Area = value;
					this.SendPropertyChanged("Area");
					this.OnAreaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fajar", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Fajar
		{
			get
			{
				return this._Fajar;
			}
			set
			{
				if ((this._Fajar != value))
				{
					this.OnFajarChanging(value);
					this.SendPropertyChanging();
					this._Fajar = value;
					this.SendPropertyChanged("Fajar");
					this.OnFajarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zuhar", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Zuhar
		{
			get
			{
				return this._Zuhar;
			}
			set
			{
				if ((this._Zuhar != value))
				{
					this.OnZuharChanging(value);
					this.SendPropertyChanging();
					this._Zuhar = value;
					this.SendPropertyChanged("Zuhar");
					this.OnZuharChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Asar", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Asar
		{
			get
			{
				return this._Asar;
			}
			set
			{
				if ((this._Asar != value))
				{
					this.OnAsarChanging(value);
					this.SendPropertyChanging();
					this._Asar = value;
					this.SendPropertyChanged("Asar");
					this.OnAsarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maghrib", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Maghrib
		{
			get
			{
				return this._Maghrib;
			}
			set
			{
				if ((this._Maghrib != value))
				{
					this.OnMaghribChanging(value);
					this.SendPropertyChanging();
					this._Maghrib = value;
					this.SendPropertyChanged("Maghrib");
					this.OnMaghribChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Isha", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Isha
		{
			get
			{
				return this._Isha;
			}
			set
			{
				if ((this._Isha != value))
				{
					this.OnIshaChanging(value);
					this.SendPropertyChanging();
					this._Isha = value;
					this.SendPropertyChanged("Isha");
					this.OnIshaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jumma", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Jumma
		{
			get
			{
				return this._Jumma;
			}
			set
			{
				if ((this._Jumma != value))
				{
					this.OnJummaChanging(value);
					this.SendPropertyChanging();
					this._Jumma = value;
					this.SendPropertyChanged("Jumma");
					this.OnJummaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
